---
# This playbook:
#  1) Performs a basic OS configuration for lab hosts.
#  2) Installs a base image of Splunk Phantom.

- name: Apply prereqs to all nodes
  hosts: all
  gather_facts: no
  roles:
    - prereqs

- name: Basic OS Configuration & Updates
  hosts: all
  roles:
    - os-config    

- name: Install Phantom
  hosts: all
  roles:
    - core-install