---
# This playbook deploys a basic Splunk Phantominstallation

- name: Apply prereqs to all nodes
  hosts: all
  gather_facts: no
  roles:
    - prereqs

- name: Install Phantom
  hosts: all
  roles:
    - core-install


