---

- name: Set the hostname as per the Ansible inventory file
  hostname:
    name: "{{ inventory_hostname }}"
  become: yes    


- name: Add "{{ os_group }}" group (so we can set ulimits)
  group:
    name: "{{ os_group }}"
    state: present  
  become: yes  

- name: Add "{{ os_user }}" user with the home dir /home/{{ os_user }}/ (so we can set ulimits)
  user:
    name: "{{ os_user }}"
    group: "{{ os_group }}"
    home: /home/{{ os_user }}/
    shell: /bin/bash
    comment: Phantom User
  become: yes


- name: -OS Updates- Clear yum caches (note this is not supported in yum module so we have to do it in command module)
  command:
    cmd: "yum clean all"
    warn: false
  become: yes

- name: -OS Updates- Check for OS package updates (excluding nginx)
  yum:
    name: "*"
    state: latest 
    exclude: nginx* 
  become: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Amazon'


- name: -Prereqs- Install EPEL repo (required to install python-pip)
  yum:
    name: epel-release
    state: present
  become: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'    

- name: -Prereqs- Seperate task to ensure that python-pip is installed regardless of version
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - python-setuptools
    - python-pip
  become: yes

- name: -Prereqs- Install Splunk Phantom prereq packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - wget
    - libevent
    - libicu
    - c-ares
    - bind-utils
    - java-1.8.0-openjdk-headless
    - mailcap
    - fontconfig
    - ntpdate
    - perl
    - rsync
    - xmlsec1
    - xmlsec1-openssl
    - libxslt
    - ntp
    - zip
    - net-tools
    - policycoreutils-python
    - libxml2
    - libcurl
    - gnutls
  become: yes
  when: 
    - phantom_version is version('5.3.0', '<')     

- name: -Prereqs- Install pexpect
  pip:
    name: pexpect>3.3
  become: yes  


- name: -ulimits- Set /etc/security/limits.conf for "{{ os_user }}" user
  template:
    src: limits.conf.j2
    dest: "/etc/security/limits.conf"
  become: yes


- name: -THP- Install disable-thp script to be run at boottime
  template:
    src: disable-thp.j2
    dest: "/usr/local/bin/disable-thp"
    mode: '0754'
  become: yes

- name: -THP- Install disable-thp systemd unit file
  template:
    src: disable-thp.service.j2
    dest: "/etc/systemd/system/disable-thp.service"
    mode: '0644'
  become: yes  

- name: -THP- Configure systemd to run disable-thp at boot time
  systemd:
    name: disable-thp
    enabled: yes
    masked: no
  become: yes

- name: -THP- Run the disable-thp script
  command: /usr/local/bin/disable-thp
  become: yes    


- name: -firewalld- Check if /usr/sbin/firewalld exists
  stat: 
    path: /usr/sbin/firewalld
  register: firewalld_flag

- name: -firewalld-  Allow tcp/80 traffic through firewalld
  firewalld:
    service: http
    permanent: yes
    state: enabled
  become: yes
  when: firewalld_flag.stat.exists == True

- name: -firewalld-  Allow tcp/{{ phantom_https_port }} traffic through firewalld
  firewalld:
    port: "{{ phantom_https_port }}/tcp"
    permanent: yes
    state: enabled
  become: yes  
  when: firewalld_flag.stat.exists == True

- name: -firewalld- Reload firewalld rules while maintaining session state (be nice to Ansible)   
  command: 
    cmd: firewall-cmd --reload
  become: yes  
  when: firewalld_flag.stat.exists == True

